<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisMode>Recommended</AnalysisMode>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <CodeAnalysisTreatWarningsAsErrors>false</CodeAnalysisTreatWarningsAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IsTestProjectName>$([System.String]::Copy('$(MSBuildProjectName)').EndsWith('.Tests'))</IsTestProjectName>
    <IsAotCompatible Condition="'$(IsTestProjectName)' != 'True'">true</IsAotCompatible>
  </PropertyGroup>
</Project>
