<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>CtrDxEditor.Desktop</RootNamespace>
    <AssemblyName>CtrDxEditor</AssemblyName>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <DesktopPublish>true</DesktopPublish>
    <PublishAot>true</PublishAot>
    <TrimMode>full</TrimMode>
    <WindowsDistributionIcon>../../distribution/icons/CtrDxEditorIcon.ico</WindowsDistributionIcon>
    <ApplicationIcon Condition="$([MSBuild]::IsOsPlatform('Windows'))">$(WindowsDistributionIcon)</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CtrDxEditor.Shared\CtrDxEditor.Shared.csproj" />
  </ItemGroup>
</Project>
