<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
  <PropertyGroup>
    <TargetFramework>net10.0-browser</TargetFramework>
    <RootNamespace>CtrDxEditor.Browser</RootNamespace>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RunAOTCompilation>true</RunAOTCompilation>
    <WasmNativeStrip>true</WasmNativeStrip>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Browser" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CtrDxEditor.Shared\CtrDxEditor.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content
      Include="..\..\distribution\icons\CtrDxEditorIcon.ico"
      Link="wwwroot\favicon.ico"
      CopyToOutputDirectory="PreserveNewest"
      CopyToPublishDirectory="PreserveNewest"
    />
  </ItemGroup>
</Project>
