<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>CtrDxEditor</RootNamespace>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <AvaloniaNameGeneratorIsEnabled>false</AvaloniaNameGeneratorIsEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Skia" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="AvaloniaDialogs" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Material.Icons.Avalonia" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CtrDxEditor.Core\CtrDxEditor.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="..\..\resources\localization\*.json"
                      Link="Localization\%(Filename)%(Extension)" />
    <AvaloniaResource Include="..\..\resources\fonts\RobotoMono-*.ttf"
                      Link="Assets\Fonts\%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
